name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: gofmt
        run: |
          diff=$(gofmt -l .)
          if [ -n "$diff" ]; then
            echo "The following files are not gofmt'd:"
            echo "$diff"
            exit 1
          fi

      - name: go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./...
